// Curated emoji set for the Studio composer picker. Kept small and dependency-
// free (no emoji-mart) — searchable by the keyword list on each entry.
export type Emoji = { char: string; keywords: string };

export const EMOJIS: Emoji[] = [
  // Smileys & people
  { char: "😀", keywords: "sourire content happy grin" },
  { char: "😃", keywords: "sourire content happy joie" },
  { char: "😄", keywords: "rire content happy" },
  { char: "😁", keywords: "sourire grin content" },
  { char: "😅", keywords: "rire sueur nerveux" },
  { char: "😂", keywords: "rire larmes lol mdr" },
  { char: "🤣", keywords: "rire roule lol mdr" },
  { char: "😊", keywords: "sourire timide content" },
  { char: "🙂", keywords: "sourire léger" },
  { char: "😉", keywords: "clin oeil wink" },
  { char: "😍", keywords: "amour coeur yeux love" },
  { char: "🤩", keywords: "star étoiles wow admiration" },
  { char: "😎", keywords: "cool lunettes soleil" },
  { char: "🤔", keywords: "réflexion penser hmm doute" },
  { char: "🤯", keywords: "explosion tête wow choc mind blown" },
  { char: "😱", keywords: "choc peur cri surprise" },
  { char: "🥳", keywords: "fête party célébration" },
  { char: "😴", keywords: "dormir sommeil fatigue" },
  { char: "🤝", keywords: "poignée main deal accord partenariat" },
  { char: "🙌", keywords: "mains levées bravo célébration" },
  { char: "👏", keywords: "applaudir bravo clap" },
  { char: "👍", keywords: "pouce ok bien like" },
  { char: "👎", keywords: "pouce bas non dislike" },
  { char: "👀", keywords: "yeux regard look attention" },
  { char: "💪", keywords: "muscle force fort motivation" },
  { char: "🙏", keywords: "prière merci please pray" },
  { char: "✍️", keywords: "écrire écriture rédiger" },
  { char: "🫡", keywords: "salut respect salute" },
  // Business & tech
  { char: "🚀", keywords: "fusée lancement croissance rocket startup" },
  { char: "📈", keywords: "graphique croissance hausse stats up" },
  { char: "📉", keywords: "graphique baisse chute down" },
  { char: "📊", keywords: "graphique barres data stats analytics" },
  { char: "💡", keywords: "idée ampoule lumière insight" },
  { char: "🎯", keywords: "cible objectif target but" },
  { char: "🔥", keywords: "feu chaud tendance hot fire" },
  { char: "⚡", keywords: "éclair rapide énergie flash" },
  { char: "✅", keywords: "check valider ok fait done" },
  { char: "❌", keywords: "croix erreur non faux" },
  { char: "⭐", keywords: "étoile star favori note" },
  { char: "🏆", keywords: "trophée gagner victoire win" },
  { char: "💰", keywords: "argent money revenu cash sac" },
  { char: "💸", keywords: "argent dépense billets" },
  { char: "💼", keywords: "travail business mallette job" },
  { char: "📱", keywords: "téléphone mobile smartphone app" },
  { char: "💻", keywords: "ordinateur laptop code dev" },
  { char: "⏰", keywords: "réveil temps heure horloge" },
  { char: "🕐", keywords: "horloge temps heure" },
  { char: "📅", keywords: "calendrier date planning" },
  { char: "📌", keywords: "épingle punaise important pin" },
  { char: "🔗", keywords: "lien chaine link url" },
  { char: "📢", keywords: "annonce mégaphone communication" },
  { char: "🧠", keywords: "cerveau intelligence idée brain" },
  { char: "🛠️", keywords: "outils réparer build dev" },
  { char: "⚙️", keywords: "engrenage réglage settings config" },
  { char: "🤖", keywords: "robot ia ai bot" },
  { char: "✨", keywords: "étincelles magie ia sparkle nouveau" },
  { char: "🎉", keywords: "fête confetti célébration party" },
  { char: "🎊", keywords: "confetti fête célébration" },
  { char: "👇", keywords: "doigt bas pointe below thread" },
  { char: "👉", keywords: "doigt droite pointe next" },
  { char: "❤️", keywords: "coeur amour love rouge" },
  { char: "💙", keywords: "coeur bleu blue" },
  { char: "🩵", keywords: "coeur bleu clair" },
  { char: "💯", keywords: "cent 100 parfait full" },
  { char: "🙃", keywords: "envers ironie sarcasme" },
  { char: "😬", keywords: "grimace gêne malaise" },
  // Objects & misc
  { char: "📝", keywords: "note écrire mémo rédiger" },
  { char: "📖", keywords: "livre lire histoire" },
  { char: "🔍", keywords: "loupe recherche chercher search seo" },
  { char: "🗂️", keywords: "dossier organiser fichiers" },
  { char: "🧵", keywords: "fil thread aiguille" },
  { char: "🌍", keywords: "monde terre global earth" },
  { char: "🌱", keywords: "pousse plante croissance début" },
  { char: "🏗️", keywords: "construction build chantier" },
  { char: "🧩", keywords: "puzzle pièce solution" },
  { char: "🔑", keywords: "clé key accès solution" },
  { char: "📦", keywords: "colis boite produit ship" },
  { char: "🛒", keywords: "panier achat vente cart" },
  { char: "☕", keywords: "café pause coffee matin" },
  { char: "🎨", keywords: "art design palette créatif" },
  { char: "🎬", keywords: "clap film vidéo reel action" },
  { char: "📸", keywords: "photo appareil caméra" },
];
